### ISSUE TITLE
Unable to load dataset

### ISSUE THREAD

**Issue by Duisterhof** [ac-rad/MVTrans#6]
Hi,

We are reaching the following issue when downloading the pre-trained model:

`Traceback (most recent call last):
  File "net_train_multiview.py", line 121, in <module>
    model = PanopticModel(hparams = hparams,
  File "/test_MVTrans/MVTrans/src/lib/net/panoptic_trainer.py", line 32, in __init__
    self.model = common.get_model(hparams)
  File "/test_MVTrans/MVTrans/src/lib/net/common.py", line 162, in get_model
    model = net_attr(hparams)
  File "/test_MVTrans/MVTrans/model/multiview_net.py", line 268, in res_fpn
    return MultiviewNet(hparams)
  File "/test_MVTrans/MVTrans/model/multiview_net.py", line 76, in __init__
    self.semanticFeature = ResnetEncoder(resnet, "pretrained")  # the features after bn and relu
  File "/test_MVTrans/MVTrans/model/networks/resnet_encoder.py", line 35, in __init__
    self.encoder = resnets[num_layers](pretrained)
  File "/env/lib/python3.8/site-packages/torchvision/models/_utils.py", line 142, in wrapper
    return fn(*args, **kwargs)
  File "/env/lib/python3.8/site-packages/torchvision/models/_utils.py", line 228, in inner_wrapper
    return builder(*args, **kwargs)
  File "/env/lib/python3.8/site-packages/torchvision/models/resnet.py", line 761, in resnet50
    weights = ResNet50_Weights.verify(weights)
  File "/env/lib/python3.8/site-packages/torchvision/models/_api.py", line 81, in verify
    obj = cls[obj.replace(cls.__name__ + ".", "")]
  File "/env/lib/python3.8/enum.py", line 387, in __getitem__
    return cls._member_map_[name]
KeyError: 'pretrained'`

Could you help us debug the problem?

Thanks!

**Comment by EterHF** [comment]
Excuse me, I failed to unzip the dataset when I tried to merge the train dataset split file using unzip command in Linux. I also tried `unzip -F` and export export UNZIP_DISABLE_ZIPBOMB_DETECTION=TRUE, but none worked for me. Can u please tell me how u manage the dataset?

**Comment by zk5120** [comment]
> Excuse me, I failed to unzip the dataset when I tried to merge the train dataset split file using unzip command in Linux. I also tried `unzip -F` and export export UNZIP_DISABLE_ZIPBOMB_DETECTION=TRUE, but none worked for me. Can u please tell me how u manage the dataset?

you can use "7z x synthetic_dataset_train_pkl_split.zip", it will create a zip file (synthetic_dataset_train_pkl.zip), then use "7z x synthetic_dataset_train_pkl.zip"
